### PR TITLE
Adding a public ip to Bastion template

### LINKED ISSUE #90: Bastion Public IP
The bastion template has an output for public ip. However, the instance does not associate one. 

Is this intentionally left for the user (as they may use VPN here) or is this an oversight?

### PR DESCRIPTION
**Pull request by moofish32**
associating a public ip address with bastion template fixes #90

### CODE REVIEW

**Comment by moofish32** [comment]
@clstokes  -- this should not have been remote master -- a little hast trying to finish before I start the day gig!

**Comment by clstokes** [comment]
Hi @moofish32, thanks for contributing this change. Though, it's strange that your bastion instance did not receive a public IP. The public subnet the instance is created within is configured to [map public IPs on launch](https://github.com/hashicorp/best-practices/blob/be01fecf77adc08dcc0be408fb2c20e8f4c8aad1/terraform/modules/aws/network/public_subnet/public_subnet.tf#L26) and in our environment received a public IP as expected.

It's better to be explicit anyway, as your change is, so thanks again!

**Comment by moofish32** [comment]
@clstokes -- Ahh! This is probably because my setup significantly modifies the subnet and vpc defaults. I have 3 AZ with 3 tier subnet configuration and first destroyed the default. The bastion subnet was a public subnet. Thank you for the merge.

**Comment by clstokes** [comment]
@moofish32 that explains it! I was really curious about that. Again, better to be explicit anyway. Cheers!

**Pull request merged**
